// =============================================================================
// SPI MASTER - RTL Design (DUT)
// =============================================================================
// SPI (Serial Peripheral Interface) Protocol:
//   - 4-wire protocol: SCLK, MOSI, MISO, CS_N
//   - Master initiates all transfers
//   - Data shifted on clock edges (configurable polarity/phase)
//   - Full duplex: sends and receives simultaneously
//
// Signals:
//   SCLK  - Serial Clock (generated by master)
//   MOSI  - Master Out Slave In  (master sends data)
//   MISO  - Master In  Slave Out (master receives data)
//   CS_N  - Chip Select, active LOW (selects the slave)
// =============================================================================

module spi_master #(
    parameter DATA_WIDTH  = 8,          // Bits per transfer (default 8)
    parameter CLK_DIV     = 4,          // SCLK = sys_clk / (2 * CLK_DIV)
    parameter CPOL        = 0,          // Clock Polarity: 0=idle low, 1=idle high
    parameter CPHA        = 0           // Clock Phase:    0=sample on 1st edge
                                        //                 1=sample on 2nd edge
) (
    // System signals
    input  logic                  clk,       // System clock
    input  logic                  rst_n,     // Active-low reset

    // CPU/Controller interface (how software talks to this block)
    input  logic                  start,     // Pulse high to begin a transfer
    input  logic [DATA_WIDTH-1:0] tx_data,   // Data to send to slave
    output logic [DATA_WIDTH-1:0] rx_data,   // Data received from slave
    output logic                  busy,      // HIGH while transfer in progress
    output logic                  done,      // Pulses HIGH when transfer complete

    // SPI bus signals (connect to actual SPI slave chip)
    output logic                  sclk,      // SPI clock to slave
    output logic                  mosi,      // Data: master -> slave
    input  logic                  miso,      // Data: slave  -> master
    output logic                  cs_n       // Chip select (active LOW)
);

    // -------------------------------------------------------------------------
    // Internal signals
    // -------------------------------------------------------------------------
    logic [$clog2(CLK_DIV)-1:0] clk_cnt;      // Clock divider counter
    logic                        sclk_en;       // Enable for SCLK generation
    logic                        sclk_rise;     // Single-cycle SCLK rising edge
    logic                        sclk_fall;     // Single-cycle SCLK falling edge
    logic [$clog2(DATA_WIDTH):0] bit_cnt;       // Counts bits transferred (0..7)
    logic [DATA_WIDTH-1:0]       tx_shift;      // Shift register for TX
    logic [DATA_WIDTH-1:0]       rx_shift;      // Shift register for RX

    // -------------------------------------------------------------------------
    // FSM State Encoding
    // -------------------------------------------------------------------------
    typedef enum logic [1:0] {
        IDLE     = 2'b00,   // Waiting for start
        CS_SETUP = 2'b01,   // Assert CS_N, wait one cycle before clocking
        TRANSFER = 2'b10,   // Shifting data bits
        CS_HOLD  = 2'b11    // Deassert CS_N after last bit
    } state_t;

    state_t state, next_state;

    // -------------------------------------------------------------------------
    // Clock Divider - generates SCLK at sys_clk / (2 * CLK_DIV)
    // -------------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            clk_cnt  <= '0;
            sclk_en  <= 1'b0;
        end else if (state == TRANSFER) begin
            sclk_en <= 1'b1;
            if (clk_cnt == CLK_DIV - 1) begin
                clk_cnt <= '0;
                sclk_en <= ~sclk_en;   // Toggle to create clock
            end else begin
                clk_cnt <= clk_cnt + 1;
            end
        end else begin
            clk_cnt <= '0;
            sclk_en <= CPOL;           // Idle state depends on polarity
        end
    end

    // Detect single-cycle edges of SCLK
    assign sclk_rise = (sclk_en && !sclk) ? 1'b1 : 1'b0;
    assign sclk_fall = (!sclk_en && sclk)  ? 1'b1 : 1'b0;
    assign sclk      = (state == TRANSFER) ? sclk_en ^ CPOL : CPOL;

    // -------------------------------------------------------------------------
    // FSM - Sequential (state register)
    // -------------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            state <= IDLE;
        else
            state <= next_state;
    end

    // -------------------------------------------------------------------------
    // FSM - Combinational (next state logic)
    // -------------------------------------------------------------------------
    always_comb begin
        next_state = state;
        case (state)
            IDLE:     if (start)               next_state = CS_SETUP;
            CS_SETUP:                           next_state = TRANSFER;
            TRANSFER: if (bit_cnt == DATA_WIDTH && (sclk_rise || sclk_fall))
                                                next_state = CS_HOLD;
            CS_HOLD:                            next_state = IDLE;
            default:                            next_state = IDLE;
        endcase
    end

    // -------------------------------------------------------------------------
    // TX Shift Register - loads data, shifts MSB first on active clock edge
    // -------------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tx_shift <= '0;
            bit_cnt  <= '0;
        end else begin
            case (state)
                IDLE: begin
                    tx_shift <= tx_data;   // Pre-load data while idle
                    bit_cnt  <= '0;
                end
                TRANSFER: begin
                    // CPHA=0: shift on falling edge, sample on rising
                    // CPHA=1: shift on rising edge, sample on falling
                    if ((CPHA == 0 && sclk_fall) || (CPHA == 1 && sclk_rise)) begin
                        tx_shift <= {tx_shift[DATA_WIDTH-2:0], 1'b0}; // Shift left
                        bit_cnt  <= bit_cnt + 1;
                    end
                end
                default: ;
            endcase
        end
    end

    // -------------------------------------------------------------------------
    // RX Shift Register - captures MISO on active sample edge
    // -------------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rx_shift <= '0;
            rx_data  <= '0;
        end else begin
            if (state == TRANSFER) begin
                // CPHA=0: sample on rising edge
                // CPHA=1: sample on falling edge
                if ((CPHA == 0 && sclk_rise) || (CPHA == 1 && sclk_fall)) begin
                    rx_shift <= {rx_shift[DATA_WIDTH-2:0], miso}; // Shift in MSB first
                end
            end else if (state == CS_HOLD) begin
                rx_data <= rx_shift;   // Latch received data when done
            end
        end
    end

    // -------------------------------------------------------------------------
    // Output assignments
    // -------------------------------------------------------------------------
    assign mosi = (state == TRANSFER) ? tx_shift[DATA_WIDTH-1] : 1'b0;
    assign cs_n = (state == IDLE || state == CS_HOLD) ? 1'b1 : 1'b0;
    assign busy = (state != IDLE);
    assign done = (state == CS_HOLD);

endmodule : spi_master


